import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { NavBar } from "@/components/navigation/NavBar";
import { ThemeProvider } from "@/components/provider/theme/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import Spacing from "@/components/elements/Spacing";
import Responsive from "@/components/utils/Responsive";
import { cn } from "@/lib/utils";
import SideNav from "@/components/navigation/SideNav";
import TopNav from "@/components/navigation/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ClerkProvider>
         <html lang="fr" suppressHydrationWarning>
            <body className={cn("w-full min-h-screen", inter.className)}>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
               >
                  {/* <Responsive /> */}
                  <TopNav />
                  {children}
                  <Toaster />
               </ThemeProvider>
            </body>
         </html>
      </ClerkProvider>
   );
}
