import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

import { cn } from "@/lib/utils";
import Responsive from "@/components/utils/Responsive";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
   title: "Next.js",
   description: "Generated by Next.js",
};

export default function OnboardingLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <ClerkProvider>
         <html lang="fr">
            <body
               className={cn(
                  "flex justify-center h-screen items-center",
                  inter.className
               )}
            >
               {children}
               <Toaster />
            </body>
         </html>
      </ClerkProvider>
   );
}
