import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import { ThemeProvider } from "@/components/provider/theme/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import SideNavBar from "@/components/admin/SideNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function AdminLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="fr" suppressHydrationWarning>
         <body className={cn("flex w-full min-h-screen", inter.className)}>
            {/* <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >  */}
               {/* SideBar */}
               <SideNavBar/> 
               {/* Main Content*/}
               <div className="p-8 w-full">{children}</div>

               <Toaster />
            {/* </ThemeProvider> */}
         </body>
      </html>
   );
}
